CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId integer references projects(id)
);

INSERT INTO projects(name,priority,description,deliverydate)
VALUES('make a web App',1,'Using python','2019-05-12');

INSERT INTO projects(name,priority,description,deliverydate)
VALUES('make a App',1,'Using Java','2021-05-12');

INSERT INTO projects(name,done,projectId)
VALUES('download Vuejs',false,1);

INSERT INTO projects(name,priority,description,deliverydate)
VALUES('make a App',1,'Using Java','2021-05-12');

INSERT INTO tasks(name,priority,description,deliverydate)
VALUES('make a mobile App',2,'Using Dart','2023-05-12');



INSERT INTO tasks(name,done,projectId)
VALUES('download Vuejs',false,1);



INSERT INTO tasks(name,done,projectId)
VALUES('create UI',false,1);

INSERT INTO tasks(name,done,projectId)
VALUES('download Flutter',false,2);

INSERT INTO tasks(name,done,projectId)
VALUES('Design UI',false,2);